on:
  push:

permissions:
    packages: read

name: check code

jobs:
  golint:
    steps:
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  fmt:
    steps:
      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './'
          gofmt-flags: '-l -d'
